# Numpy

Numpy is a general perpose array processing package.It provides a high level performance multidimwntion array object and tool for woorking with these array.It is the fundamental package for scitific computing with python.

In [1426]:
import numpy as np# importing

In [1427]:
np.__version__  #to check the version

'2.0.2'

# Array


An array is data structure that stores values of same data type.In python yhis is the main difference between array and list. while python list can contain values corresponding to different data types,array in python can only contain values corresponding to same data type.

1D Array
a = np.array([10, 20, 30])

2D Array
b = np.array([[1, 2, 3], [4, 5, 6]])

3D Array
c = np.array([[[1], [2]], [[3], [4]]])


In [1428]:
# create a array
#np.array()
#np.arange()
#np.linesapsce()
#np.random.randint()
#np.randdom.rand ()
#np.randdom.randn()
#np.zeros
#np.once()
#np.identity(),np.eye()

In [1429]:
#here, arr is existing array, and np
#Creation of array
#array():- to create an array
#Syntax:- np.array(collection,dtype = dt_name)
a= np.array((10,20,"duniya"))
print(type(a))  #it will repreant the type of array
a.dtype
print(a) # datatypes of the elements present inside the collection

<class 'numpy.ndarray'>
['10' '20' 'duniya']


In [1430]:
arr = np.array([2,3,5])
print(arr.dtype)
type(arr)
print(arr)  # to get the dimention of array
arr.shape  # to know the no.of rows and coloumns
#in case of 2D array--> o/p--> (no of coloumns,)
#3D array--> o/p--> (no.of rows, no.of coloumns)
#4D array--> o/p--> (no of rows,columns,no.of elements in each column)
arr1=np.array([[1,2],[7,8],[5,4]])
arr1.shape
print(arr1)
# creation of 3D array
arr2 = np.array([[[3,6,8],[10,20,30],[6,5,2003]]])
print(arr2)
ar = np.array([[[6,5,2003]]])
ar.shape
print(ar)

int64
[2 3 5]
[[1 2]
 [7 8]
 [5 4]]
[[[   3    6    8]
  [  10   20   30]
  [   6    5 2003]]]
[[[   6    5 2003]]]


In [1431]:
np.array([[[1,2],[2,7],[5,4]]])

array([[[1, 2],
        [2, 7],
        [5, 4]]])

In [1432]:
# create an array of shape(3,3,2)
np.array([[[1,2],[2,7],[5,4]],[[5,4],[7,5],[8,9]],[[2,7],[3,6],[7,2]]])

# to create a sequence of numbers
# syntax:- np.arange(sv,ev+-1,sv)
np.arange(0,10,2)


array([0, 2, 4, 6, 8])

In [1433]:
# it will give you the equally spaced values
#syntax is (sv,ev,no_of_elements) note: ev is inclusive
np.linspace(1,6,10)

array([1.        , 1.55555556, 2.11111111, 2.66666667, 3.22222222,
       3.77777778, 4.33333333, 4.88888889, 5.44444444, 6.        ])

In [1434]:
np.random.randint(1,10,3)# starting and ending values is inclusive,#random is a module and randint is a function
np.random.rand(6)# rand() is used to generate the generated desire no. of random values b/w 0 to 1 , here 6 is no. of values it will print
np.random.randn()# randn() is used to generte random values b/w range -1 to +1 , passing values inside the function is optional, if passing the values it will generate that many numbers
#randn()and rand() -by deafault it will generate 1 values

1.5196931610526028

In [1435]:
np.random.rand(6)

array([0.54758194, 0.42765648, 0.64293486, 0.65917994, 0.15793874,
       0.41630011])

In [1436]:
np.random.randn(7)

array([-1.13229638,  1.31894986, -0.84663937, -0.46266054, -0.16794079,
       -0.69523303, -0.00775123])

In [1437]:
np.random.randint(5,10,4)

array([6, 9, 8, 5])

In [1438]:
#create a 3D array using randint
arr=np.random.randint(1,20,(3,3,2))#3-column,3-row,2values
print(arr)
print(arr.ndim)

[[[16  8]
  [18 19]
  [13 17]]

 [[13 11]
  [14 14]
  [ 6 14]]

 [[13  5]
  [10  1]
  [ 1 10]]]
3


In [1439]:
#np.zeros(argument)
print(np.zeros(2))# zeros of 1D array,here zeros are function- will generate the array of zeros,will take only one arg
print(np.zeros((2,3)))# 2D array ,whereascollection can be tuple or list
np.zeros([2,3,2])# 3D array

[0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [1440]:
#np.ones()
print(np.ones(2))# 1D array
print(np.ones((4,2)))# 2D array
print(np.ones((2,2,2)))# 3D array

[1. 1.]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [1441]:
print(np.identity((3)))# n*n matrix
print(np.eye((3)))#identity matrix,only 2D array,

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [1442]:
# Array filled with a constant
full = np.full((2, 2), 7)

# Array Properties:

arr.shape        # Dimensions (rows, columns)

arr.ndim         # Number of dimensions

arr.size         # Total number of elements


arr.dtype        # Data type of elements

arr.itemsize    # bytes per element

arr.nbytes      # total bytes

In [1443]:
#Using arr.reshape() will give a new shape to an array without changing the data
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [1444]:
b = a.reshape(3, 2)#row,column
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [1445]:
#using arr.flatten()it will convert any array to 1D array
arr=np.array([[[1,2],[2,7],[5,4]],[[5,4],[7,5],[8,9]],[[2,7],[3,6],[7,2]]])
print(arr.shape)
print(arr.flatten())

(3, 3, 2)
[1 2 2 7 5 4 5 4 7 5 8 9 2 7 3 6 7 2]


In [1446]:
s=np.array([[1,2,3,4,5,6],[1,7,53,22,16,7]])
s

array([[ 1,  2,  3,  4,  5,  6],
       [ 1,  7, 53, 22, 16,  7]])

In [1447]:
print(s[0][-1])

6


Indexing


In [1448]:
data = np.array([1, 2, 3])
data.dtype.name

'int64'

In [1449]:
data[1]

np.int64(2)

In [1450]:
data[::-1]

array([3, 2, 1])

In [1451]:
data[-2:]

array([2, 3])

In [1452]:
s=np.array([[1,2,3,4,5,6],[1,7,53,22,16,7]])

In [1453]:
s[:3:,-3:]#first 3 last 3

array([[ 4,  5,  6],
       [22, 16,  7]])

In [1454]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
len(a)

3

In [1455]:
print(a[a < 5])

[1 2 3 4]


In [1456]:
b=a[a%2==0]
print(b)

[ 2  4  6  8 10 12]


In [1457]:
c=b[(b>2) & (b<10)]
print(c)

[4 6 8]


In [1458]:
a=np.array([[[1,2],[2,7],[5,4]],[[5,4],[7,5],[8,9]],[[2,7],[3,6],[7,2]]])

In [1459]:
a[::-1]

array([[[2, 7],
        [3, 6],
        [7, 2]],

       [[5, 4],
        [7, 5],
        [8, 9]],

       [[1, 2],
        [2, 7],
        [5, 4]]])

In [1460]:
a[2][1]

array([3, 6])

In [1461]:
a[0][1][1]

np.int64(7)

In [1462]:
a[2][::-1]

array([[7, 2],
       [3, 6],
       [2, 7]])

In [1463]:
a=np.random.randint(1,10,(3,3,4))
print(a)

[[[9 8 4 2]
  [4 2 3 2]
  [7 8 2 2]]

 [[5 8 1 1]
  [3 7 7 8]
  [8 5 5 5]]

 [[9 2 7 5]
  [2 4 5 2]
  [1 9 2 2]]]


In [1464]:
b=a[1][1]
print(b)

[3 7 7 8]


In [1465]:
b[b>2]#boolean filtering

array([3, 7, 7, 8])

In [1466]:
a=np.array([[[1,2,3,4,5],[3,4,5,6,7],[6,8,10,11,12]],[[13,14,15,17,18],[3,4,6,8,9],[8,9,4,6,8]]])
last_elements = a[:, :, -1]
print(last_elements)

[[ 5  7 12]
 [18  9  8]]


In [1467]:
last_elements = a[:, :, -1]
print(last_elements)

[[ 5  7 12]
 [18  9  8]]


In [1468]:
a = np.array([1, 2, 3, 4])
arr=a[np.newaxis,:]
arr

array([[1, 2, 3, 4]])

In [1469]:
a=np.array([9,3,5])
b=np.sort(a)
print(b)

[3 5 9]


Operations on array

There kinds of operation we perform in array
i) array to array
ii)array with scaler operations
iii)array with inbuild operations

to perform operation we required two array should be of same dimension and same no. of elements

In [1470]:
a = np.array([5,6,7])
b=np.array([8,9,3])

print(a|b)
print(a in b)
print(a is b)
print(a>>2)
print(a&b)


[13 15  7]
False
False
[1 1 1]
[0 0 3]


Array with scaler operation/constrant

In [1471]:
a = np.array([1,2,3,4])
print(a+10)
print(a-20)
print(a*10)
print(a/10)
print(a%10)
print(a//2)
print(a>5)
print(a<6)
print(a==7)
print(a>=5)
print(a<=5)
print(a<<2)
print(a>>2)

[11 12 13 14]
[-19 -18 -17 -16]
[10 20 30 40]
[0.1 0.2 0.3 0.4]
[1 2 3 4]
[0 1 1 2]
[False False False False]
[ True  True  True  True]
[False False False False]
[False False False False]
[ True  True  True  True]
[ 4  8 12 16]
[0 0 0 1]


array with inbuild function or aggreigate function

In [1472]:
a = np.array([-1,2,2,-3,4])#np.mode(var) will not work
b=abs(a)
print(b.sum())
print(np.mean(b))
print(np.median(b))
print(np.std(b))
print(np.corrcoef(b))
print(np.cumsum(b))
print(b.max())
print(b.min())

12
2.4
2.0
1.019803902718557
1.0
[ 1  3  5  8 12]
4
1


In [1473]:
a=np.array([1,2,3])
b=np.array([3,4,5])
print(np.concatenate((a,b),axis=0))#np.concatenate((ar1,ar2),axis=0)
print(np.dot(a,b))#prouct aXb

[1 2 3 3 4 5]
26


#Aggregate Functions
arr = np.array([[1, 2, 3], [4, 5, 6]])

np.sum(arr)         # 21

np.sum(arr, axis=0) # [5, 7, 9] - column-wise

np.mean(arr)        # 3.5

np.min(arr)         # 1

np.max(arr)         # 6

np.std(arr)         # 1.707...

# Matrix Operations

In [1474]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [1475]:
# Transpose
a.T

array([[1, 3],
       [2, 4]])

In [1476]:
# Inverse (if square & invertible)
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [1477]:
# Determinant
np.linalg.det(a)

np.float64(-2.0000000000000004)

#  Combining Arrays

In [1478]:
# Horizontal stack (column-wise)
np.hstack((a, b))  # [[1 2 3 4]]

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [1479]:
# Vertical stack (row-wise)
np.vstack((a, b))  # [[1 2], [3 4]]

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [1480]:
# Concatenate
np.concatenate((a, b), axis=0)  # same as vstack

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

#Splitting Arrays

In [1481]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [1482]:
# Split into 3 columns
np.hsplit(a, 3)

[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]])]

In [1483]:
# Split into 2 rows
np.vsplit(a, 2)

[array([[1, 2, 3]]), array([[4, 5, 6]])]

# Broadcasting

In [1484]:
a = np.array([1, 2, 3])
b = 2

In [1485]:
a + b

array([3, 4, 5])

In [1486]:
# Broadcasting in 2D
m = np.array([[1], [2], [3]])
n = np.array([10, 20, 30])

In [1487]:
m + n

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

# Mathematical Functions
x = np.array([1, 4, 9])

np.sqrt(x)       # [1. 2. 3.]

np.exp(x)        # [2.71, 54.59, 8103.08]

np.log(x)        # [0.0, 1.386, 2.197]

np.sin(x)        # Trigonometric sine

np.abs([-1, -2]) # [1 2]

# Statistical Functions
a = np.array([[1, 2], [3, 4]])

np.mean(a)       # 2.5

np.median(a)     # 2.5

np.std(a)        # Standard deviation

np.var(a)        # Variance

np.min(a)        # 1

np.max(a)        # 4

np.sum(a, axis=0)  # Column sum: [4, 6]

np.sum(a, axis=1)  # Row sum: [3, 7]

#  Working with Data in NumPy

 1. Reading and Writing Data with NumPy

NumPy provides methods to read/write data in text and binary formats.

 Load from a CSV or text file

data = np.loadtxt('data.txt', delimiter=',')

Load with missing values and specific dtype

data = np.genfromtxt('data.csv', delimiter=',', dtype=float, skip_header=1)

 Load binary .npy file

arr = np.load('array.npy')
