In [ ]:
import numpy as np

In [ ]:
a=np.linspace(0,50,10)
a

array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

In [ ]:
b=np.random.randint(5,20,(3,3))
b

array([[ 8, 19, 11],
       [13, 17, 15],
       [12, 12, 13]])

In [ ]:
print(a.ndim)
print(b.ndim)

1
2


In [ ]:
n=np.arange(0,50,1)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
r=a.reshape((2,5))
print(r)

[[ 0.          5.55555556 11.11111111 16.66666667 22.22222222]
 [27.77777778 33.33333333 38.88888889 44.44444444 50.        ]]


In [ ]:
f = r.flatten()
print(f)

[ 0.          5.55555556 11.11111111 16.66666667 22.22222222 27.77777778
 33.33333333 38.88888889 44.44444444 50.        ]


In [ ]:
b

array([[ 8, 19, 11],
       [13, 17, 15],
       [12, 12, 13]])

In [ ]:
s=b[1:]
s

array([[13, 17, 15],
       [12, 12, 13]])

In [ ]:
z=b[1:2,1:]
z

array([[17, 15]])

In [ ]:
print(a[::-1])

[50.         44.44444444 38.88888889 33.33333333 27.77777778 22.22222222
 16.66666667 11.11111111  5.55555556  0.        ]


In [ ]:
o=np.linspace(1,10,10)
o

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
a=np.linspace(0,50,10)
a

array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

In [ ]:
print(o)
print(a)


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.          5.55555556 11.11111111 16.66666667 22.22222222 27.77777778
 33.33333333 38.88888889 44.44444444 50.        ]


In [ ]:
print(o+a)
print(a*o)
print(a-5)
print(o-5)

[ 1.          7.55555556 14.11111111 20.66666667 27.22222222 33.77777778
 40.33333333 46.88888889 53.44444444 60.        ]
[  0.          11.11111111  33.33333333  66.66666667 111.11111111
 166.66666667 233.33333333 311.11111111 400.         500.        ]
[-5.          0.55555556  6.11111111 11.66666667 17.22222222 22.77777778
 28.33333333 33.88888889 39.44444444 45.        ]
[-4. -3. -2. -1.  0.  1.  2.  3.  4.  5.]


In [ ]:
np.random.rand(5)

array([0.02891618, 0.41497762, 0.92390206, 0.39914534, 0.19507919])

In [ ]:
np.random.randn(5)

array([ 0.99549785, -1.48581071,  0.18527631,  1.96785516,  0.38330693])

In [ ]:
b

[2, 34, 5]

In [ ]:
c=b.copy()
c[0]=[1,2,3]
print(c)

[[1, 2, 3], 34, 5]


In [ ]:
print(c)
print(b)

[[1, 2, 3], 34, 5]
[2, 34, 5]


In [ ]:
d=np.random.randint(1,10,(2,3))
d


array([[4, 8, 4],
       [9, 3, 8]])

In [ ]:
b[1]=3
b

[2, 3, 5]

In [ ]:
b=np.arange(1,5)
print(b)

[1 2 3 4]


In [ ]:
arr=b.view()
arr

array([1, 2, 3, 4])

In [ ]:
arr[0]=4
arr

array([4, 2, 3, 4])

In [ ]:
print(b)
print(arr)

[4 2 3 4]
[4 2 3 4]


In [ ]:
n=int(input("Enter a Number:"))
z=np.random.randint(1,10,(n,n))
print(z)

Enter a Number:5
[[2 6 5 3 9]
 [2 2 2 8 7]
 [7 4 3 3 6]
 [6 5 7 8 2]
 [9 6 5 1 3]]


In [ ]:
print(z.sum())

121
